VCTK-SI[Tacotron2]:
  use_phonemes: True
  phoneme_language: "en-us"
  datasets_root: "/raid/hhemati/Datasets/Speech/CL-TTS"
  dataset_name: "VCTK"
  benchmark: "vctk-spk-inc"

  speaker_lists:
    [
      ["vctk_p335"],
      ["vctk_p376"]
    ]
  model_name: "Tacotron2"
  model:
    use_d_vector_file: True
    d_vector_dim: 256

  # ==================== Optimizer
  optimizer: "Adam"
  optimizer_params:
    lr: 0.001
